config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(Digest::SHA256.hexdigest(username),
                                                Digest::SHA256.hexdigest(ENV.fetch('HTTP_USERNAME', nil))) &
      ActiveSupport::SecurityUtils.secure_compare(Digest::SHA256.hexdigest(password),
                                                  Digest::SHA256.hexdigest(ENV.fetch('HTTP_PASSWORD', nil)))
  end
  mount Sidekiq::Web => '/sidekiq'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :data_services, only: %i[create]
    end
  end

  resources :data_resources, only: %i[index]
  resources :data_services, only: %i[show]
  root 'home#index'
end

app/models/data_resource.rb
# frozen_string_literal: true

class DataResource < ApplicationRecord
  belongs_to :resourceable, polymorphic: true
  belongs_to :publisher, class_name: 'Organisation'
  belongs_to :source, optional: true
  has_many :creations, dependent: :destroy
  has_many :creators, through: :creations, class_name: 'Organisation', source: :organisation
  has_many :related_resources, dependent: :destroy
  has_many :related_data_resources, through: :related_resources, class_name: 'DataResource'

  enum :access_rights, { INTERNAL: 0, OPEN: 1, COMMERCIAL: 2 }
  enum :security_classification, { OFFICIAL: 0, SECRET: 1, TOP_SECRET: 2 }

  include PgSearch::Model
  pg_search_scope :search,
                  against: { title: 'A', description: 'B', summary: 'C' },
                  associated_against: { publisher: { name: 'D' } },
                  using: { tsearch: { prefix: true, dictionary: 'english' } }

  def summary
    read_attribute(:summary).presence || description&.truncate(250)
  end
end

app/controllers/data_resources_controller.rb
# frozen_string_literal: true

class DataResourcesController < ApplicationController
  def index
    @pagy, @data_resources = pagy(DataResources::Fetcher.call(query: params[:query], filters: params[:filters]))
    @organisations = Organisation.joins(:published_resources).distinct.id_name_order_asc
  end
end

app/views/data_resources/_data_resource.html.erb
<li>
  <h2 class="govuk-heading-m govuk-!-margin-bottom-1">
    <%= link_to data_resource.title, data_service_path(data_resource.resourceable), "data-cy": "data-service-#{data_resource.title}-link", class: "govuk-link" %>
  </h2>
  <p class="govuk-!-font-weight-bold govuk-!-margin-bottom-1" data-cy="data-service-<%= data_resource.publisher.name %>-organisation-name"><%= data_resource.publisher.name %></p>
  <p data-cy="data-service-<%= data_resource.publisher.name %>-description"><%= data_resource.summary %></p>
  <hr>
</li>

app/views/data_resources/_filters.html.erb
<%= form_with url: data_resources_path, method: :get, "data-cy": "data-service-search-form", class: "govuk-form-group" do |form|  %>
  <div class="moj-filter">
    <div class="moj-filter__header">
      <div class="moj-filter__header-title">
        <h2 class="govuk-heading-m">Filter by organisation</h2>
      </div>
      <div class="moj-filter__header-action">
      </div>
    </div>

    <div class="moj-filter__content">
      <% if params[:filters].present? %>
        <div class="moj-filter__selected">
          <div class="moj-filter__selected-heading">
            <div class="moj-filter__heading-title">
              <h2 class="govuk-heading-m">Selected filters</h2>
            </div>
            <div class="moj-filter__heading-action">
              <%= link_to "Clear filters", data_resources_path({query: params[:query].presence}.compact), class: "govuk-link govuk-link--no-visited-state", "data-cy": "data-service-clear-filters-button" %>
            </div>
          </div>
          <h3 class="govuk-heading-s govuk-!-margin-bottom-0">Organisations</h3>
          <%= render_filter_tags(params[:filters], @organisations) %>
        </div>
      <%end%>
      <%= render 'shared/filter_expander', locals: {form: form}%>
    </div>
  </div>
<%end%>

app/views/data_resources/index.html.erb
<h1 class="govuk-heading-xl">Find government data</h1>
<%= form_with url: data_resources_path, method: :get, "data-cy": "data-service-search-form", class: "govuk-form-group" do |form|  %>
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds-from-desktop">
      <%= render 'shared/search' %>
    </div>
  </div>
  <div class="govuk-grid-row govuk-!-margin-top-5">
    <div class="govuk-grid-column-one-third">
      <%= render 'data_resources/filters', locals: {form: form} %>
    </div>
    <div class="govuk-grid-column-two-thirds">
        <%= render 'shared/results_message' %>
      <ul class="govuk-list data-services" data-cy="data-service-organisation-list">
        <%= render partial: 'data_resource', collection: @data_resources %>
      </ul>
        <%= render 'shared/pagination_nav' %>
    </div>
  </div>
<% end -%>