config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Rswag::Api::Engine => '/api-docs'
  mount Rswag::Ui::Engine => '/api-docs'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(Digest::SHA256.hexdigest(username),
                                                Digest::SHA256.hexdigest(ENV.fetch('HTTP_USERNAME', nil))) &
      ActiveSupport::SecurityUtils.secure_compare(Digest::SHA256.hexdigest(password),
                                                  Digest::SHA256.hexdigest(ENV.fetch('HTTP_PASSWORD', nil)))
  end
  mount Sidekiq::Web => '/sidekiq'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :data_services, only: %i[create]
    end
  end

  resources :data_resources, only: %i[index]
  resources :data_services, only: %i[show]
  root 'home#index'
end

app/views/shared/_back-button.html.erb
<%= link_to 'Back', :back, class: "govuk-back-link", "data-cy": "govuk-back-link" %>

app/views/shared/_back_button.html.erb
<%= link_to 'Back', "javascript:history.back()", class: "govuk-back-link", "data-cy": "govuk-back-link" %>

app/views/shared/_dwp_logo.erb
<%= render "govuk_publishing_components/components/organisation_logo", 
  { organisation: {
    name: "Department for Work and Pensions", 
    crest: "single-identity", 
    brand: "department-for-work-pensions",
    id: organisation.name + "-filter-link",
    }
  } 
%>

app/views/shared/_filter.html.erb
<%= form_with url: data_services_path, method: :get, "data-cy": "data-service-search-form", class: "govuk-form-group" do |form|  %>
  <h1 class="govuk-heading-m">
    Filter by organisation
  </h1>
  <div class="govuk-button-group">
    <%= render 'shared/apply_filters_button' %>
    <% if params[:filters].present? %>
      <%= render 'shared/clear_filters_button' %>
    <%end%>
  </div>
  <fieldset class="govuk-fieldset">
    <legend class="govuk-fieldset__legend govuk-fieldset__legend--s">
    Organisations
    </legend>
    <div class="govuk-checkboxes--small" data-module="govuk-checkboxes">
      <% @organisations.each do |organisation| %>
        <div class="govuk-checkboxes__item" data-cy="organisation-<%= organisation.name %>-checkbox">
          <%= form.check_box :filters, {:multiple => true, class: "govuk-checkboxes__input", "data-cy": "organisation-#{organisation.name}-checkbox-input", checked: params[:filters]&.include?(organisation.id) }, organisation.id, nil %>
          <%= form.label :filters, "#{organisation.name}", for: "filters_#{organisation.id}", "data-cy": "data-service-search-label", class: "govuk-label govuk-checkboxes__label" %>
        </div> 
      <%end%>
    </div>
  </fieldset>
<%end%>

app/views/shared/_filter_expander.html.erb
<%= form_with url: data_resources_path, method: :get, "data-cy": "data-service-search-form", class: "govuk-form-group" do |form|  %>
  <div class="moj-filter__options">
    <%= button_tag "Apply filters", type: :submit, name: nil, class: "govuk-button", "data-cy": "data-service-apply-filters-button", "data-module": "govuk-button" %>
    <div class="govuk-form-group">
      <div class="app-c-expander" data-module="expander" data-open-on-load="true" data-expander-module-started="true">
        <h3 class="app-c-expander__heading">
          <button class="app-c-expander__button js-button" type="button" aria-expanded="true" aria-controls="expander-content-df6fa73d">Organisations</button>
          <div class="app-c-option-select__selected-counter js-selected-counter"> <%= params[:filters].present? ? params[:filters].length : 0 %> selected</div>
          <svg version="1.1" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" class="app-c-expander__icon app-c-expander__icon--up" aria-hidden="true" focusable="false"><path d="m798.16 609.84l-256-256c-16.683-16.683-43.691-16.683-60.331 0l-256 256c-16.683 16.683-16.683 43.691 0 60.331s43.691 16.683 60.331 0l225.84-225.84 225.84 225.84c16.683 16.683 43.691 16.683 60.331 0s16.683-43.691 0-60.331z"></path></svg>
          <svg version="1.1" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg" class="app-c-expander__icon app-c-expander__icon--down" aria-hidden="true" focusable="false"><path d="m225.84 414.16l256 256c16.683 16.683 43.691 16.683 60.331 0l256-256c16.683-16.683 16.683-43.691 0-60.331s-43.691-16.683-60.331 0l-225.84 225.84-225.84-225.84c-16.683-16.683-43.691-16.683-60.331 0s-16.683 43.691 0 60.331z"></path></svg>
        </h3>
        <div class="app-c-expander__content js-content app-c-expander__content--visible" id="expander-content-df6fa73d">
          <div class="govuk-checkboxes--small" data-module="govuk-checkboxes">
            <% @organisations.each do |organisation| %>
              <div class="govuk-checkboxes__item" data-cy="organisation-<%= organisation.name %>-checkbox">
                <%= form.check_box :filters, {:multiple => true, class: "govuk-checkboxes__input", "data-cy": "organisation-#{organisation.name}-checkbox-input", checked: params[:filters]&.include?(organisation.id) }, organisation.id, nil %>
                <%= form.label :filters, "#{organisation.name}", for: "filters_#{organisation.id}", class: "govuk-label govuk-checkboxes__label" %>
              </div> 
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/shared/_footer.html.erb
<footer class="govuk-footer " role="contentinfo">
  <div class="govuk-width-container ">
    <div class="govuk-footer__meta">
      <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">
          <h2 class="govuk-visually-hidden">Footer links</h2>
        <svg aria-hidden="true" focusable="false" class="govuk-footer__licence-logo", data-cy="govuk-footer-licence-logo" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 483.2 195.7" height="17" width="41">
          <path fill="currentColor" d="M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145"></path>
        </svg>
        <span class="govuk-footer__licence-description", data-cy="govuk-footer-licence-description">
            All content is available under the
            <a class="govuk-footer__link" data-cy="govuk-footer-licence-link" href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated
        </span>
      </div>
      <div class="govuk-footer__meta-item">
        <a class="govuk-footer__link govuk-footer__copyright-logo" data-cy="govuk-footer-copyright-logo" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">© Crown copyright</a>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_head.html.erb
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Data Catalogue</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "moj-frontend.min.css" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag 'moj-frontend.min' %>
  <%= render 'shared/plausible_script' %>
</head>

app/views/shared/_pagination_nav.html.erb
<div class="govuk-!-margin-bottom-3">
    <% if @pagy.count > 0 %>
        <%= govuk_pagination(pagy: @pagy) %>
        <div class="govuk-body govuk-!-margin-bottom-1">Showing <span class="govuk-!-font-weight-bold"><%= @pagy.from %></span>
            to <span class="govuk-!-font-weight-bold"><%= @pagy.to %></span> of <span class="govuk-!-font-weight-bold"><%= @pagy.count %></span> results</div>
        </div>
    <% end %>
</div>

app/views/shared/_phase-banner.html.erb
<div class="govuk-phase-banner">
  <p class="govuk-phase-banner__content", data-cy="govuk-phase-bannner-content">
    <strong class="govuk-tag govuk-phase-banner__content__tag">
      alpha
    </strong>
    <span class="govuk-phase-banner__text">
      This is a new service – your <a class="govuk-link" href="#", data-cy="govuk-phase-bannner-link">feedback</a> will help us to improve it.
    </span>
  </p>
</div>

app/views/shared/_phase_banner.html.erb
<div class="govuk-phase-banner">
  <p class="govuk-phase-banner__content" data-cy="govuk-phase-bannner-content">
    <strong class="govuk-tag govuk-phase-banner__content__tag">
      alpha
    </strong>
    <span class="govuk-phase-banner__text">
      This is a new service – your <a class="govuk-link" href="<%= ENV["FEEDBACK_URL"] %>" data-cy="govuk-phase-bannner-link">feedback</a> will help us to improve it.
    </span>
  </p>
</div>

app/views/shared/_plausible_script.html.erb
<% if ENV["PLAUSIBLE_DOMAIN"] %>
    <script defer data-domain="<%= ENV["PLAUSIBLE_DOMAIN"] %>"  src="https://plausible.io/js/script.manual.js"></script>
    <!-- define the `plausible` function to manually trigger events -->
    <script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>
    <!-- trigger pageview -->
    <script>
        function prepareUrl(params) {
        const url = new URL(location.href)
        const queryParams = new URLSearchParams(location.search)
        let customUrl = url.protocol + "//" + url.hostname + url.pathname.replace(/\/$/, '')
        for (const paramName of params) {
            const paramValue = queryParams.get(paramName)
            if (paramValue) customUrl = customUrl + '/' + paramValue
        }
        return customUrl
        }
        plausible('pageview', { u: prepareUrl(["query"]) });
    </script>
<% end %>

app/views/shared/_results_message.html.erb
<div class="results-container">
  <% if @data_resources.size > 0 %>
    <h2 class="govuk-heading-l" data-cy="data-services-results-count"><%= @pagy.count %> results</h2>
  <% else %><p class="govuk-heading-l">0 results</p>
    <div class="no-results govuk-!-font-size-19"> 
      <p class="govuk-body govuk-!-font-weight-bold">There are no matching results.</p>
        <p class="govuk-body">Improve your search results by:</p> 
        <ul class="govuk-list govuk-list--bullet"> 
          <li>removing filters</li> 
          <li>double-checking your spelling</li> 
          <li>using fewer keywords</li> 
          <li>searching for something less specific</li> 
      </ul>
    </div>
  <%end%>
</div>

app/views/shared/_search.html.erb
<%= render "govuk_publishing_components/components/search", {
  name: :query,
  on_govuk_blue: local_assigns[:on_govuk_blue] || false,
  label_text: "Search the Data Catalogue",
  value: params[:query],
  id: "data-service-search-input"
} %>